### ISSUE TITLE
R-IDE menu on mac os not available anymore

### ISSUE THREAD

**Issue by albertostefanelli** [REditorSupport/sublime-ide-r#12]
Fresh install of R-IDE and sublime. 

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1005, in run_
    return self.run(**args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Packages/Default.sublime-package/settings.py", line 101, in run
AttributeError: 'NoneType' object has no attribute 'replace'
Unable to open /Users/serg/Library/Application Support/Sublime Text 3/Packages/User/R-IDE.sublime-settings
```

**Comment by randy3k** [comment]
I guess you may have a corrupted setting file.

**Comment by albertostefanelli** [comment]
i removed /Library/Application Support/Sublime Text 3 and sublime text completely

**Comment by randy3k** [comment]
Maybe try restarting Sublime Text

**Comment by albertostefanelli** [comment]
Restarting sublime did not work but rebooting worked. 

Thanks!
