### ISSUE TITLE
Frequent crashes with rlang

### ISSUE THREAD

**Issue by mtalluto** [REditorSupport/sublime-ide-r#24]
I am experiencing very frequent crashes with rlang. There is very little information given, just "Language server rlang has crashed, do you want to restart it?"

I can't find an exact behaviour to reproduce the bug, other than it seems to be most frequent when starting a new document, newly opening a document, or changing tabs to a document (a .R file in all cases). In all cases restarting rlang seems to resolve any issues.

Sublime Text v 3.1.1, running on macOS 10.14.2.

**Comment by randy3k** [comment]
I do sometimes also get the same error, but it is definitely not "very frequent". Could you try upgrading both `LSP` and `languageserver`?

**Comment by stubedston** [comment]
I'm also experiencing what OP describes: frequent crashing with the same message box when I open a new file or switch tabs. Checking the console in sublime gives:

```
Failure writing to stdout
Traceback (most recent call last):
  File "/home/username/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 226, in write_stdin
    self.process.stdin.write(msgbytes)
BrokenPipeError: [Errno 32] Broken pipe

Failure writing to stdout
Traceback (most recent call last):
  File "/home/username/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 227, in write_stdin
    self.process.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

Failure writing to stdout
Traceback (most recent call last):
  File "/home/username/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 227, in write_stdin
    self.process.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

Sublime v3.2.1
R-IDE v0.1.8
LSP v0.8.4
languageserver v0.2.9
Ubuntu 16.04

**Comment by stubedston** [comment]
Just to note, this from the errors this is unrelated to `sublime-r-ide` and is more to do with `LSP`. However, this is no longer an issue for me after I setup the following `rlang` client in `LSP` settings:

```
"rlang":
{
    "command":
    [
        "R --quiet --slave -e languageserver::run()"
    ],
    "enabled": true,
    "languageId": "r",
    "scopes":
    [
        "source.r",
        "text.html.markdown.rmarkdown"
    ],
    "syntaxes":
    [
        "Packages/R/R.sublime-syntax",
        "Packages/R-IDE/R Markdown.sublime-syntax"
    ]
}
```

Additionally, I was having trouble in R generally with `rlang` raising errors and warnings inappropriately. This was fixed by installing the dev version at:

https://github.com/r-lib/rlang
